### ISSUE TITLE
Method name clash when refining a void({Byte*}) method in a complex type hierarchy

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2040] opened 2015-02-04 09:20 UTC
I found this one when trying to make a VFS: compiling

```ceylon
shared interface File<out FilePath, out DirectoryPath>
		given  FilePath      satisfies AbsolutePath<
                                                File<FilePath, DirectoryPath>, 
                                                Directory<FilePath, DirectoryPath>> 
		given  DirectoryPath satisfies AbsolutePath<
                                                File<FilePath, DirectoryPath>, 
                                                Directory<FilePath, DirectoryPath>> 
{
	shared formal void writeAllBytes({Byte *} bytes); 
}

shared interface Directory<out FilePath, out DirectoryPath>
		given  FilePath      satisfies AbsolutePath<
                                        File<FilePath, DirectoryPath>, 
                                        Directory<FilePath, DirectoryPath>> 
		given  DirectoryPath satisfies AbsolutePath<
                                        File<FilePath, DirectoryPath>, 
                                        Directory<FilePath, DirectoryPath>>
{
}

shared interface AbsolutePath<out ActualFile, out ActualDirectory> 
		given ActualFile      satisfies File <
                                AbsolutePath<ActualFile, ActualDirectory>, 
                                AbsolutePath<ActualFile, ActualDirectory>>
        
		given ActualDirectory satisfies Directory<
                                AbsolutePath<ActualFile, ActualDirectory>, 
                                AbsolutePath<ActualFile, ActualDirectory>>
{
}
        
//

shared class DiskAbsolutePath() satisfies AbsolutePath<DiskFile, DiskDirectory>{}

shared class DiskDirectory() satisfies Directory<DiskAbsolutePath, DiskAbsolutePath>{}

shared class DiskFile() satisfies File<DiskAbsolutePath, DiskAbsolutePath>
{
    shared actual void writeAllBytes({Byte *} bytes) {}  // Name clash ???
}
```
prints:
```
error: DiskFile is not abstract and does not override abstract method writeAllBytes(Iterable) in File
source/org/jpragey/ceylon/vfs/core/run.ceylon:42: error: name clash: writeAllBytes(Iterable<? extends Byte,? extends Object>) in DiskFile and writeAllBytes(Iterable<? extends Byte,? extends Object>) in File have the same erasure, yet neither overrides the other
    shared actual void writeAllBytes({Byte *} bytes) {}  // TODO: compiler bug???
           ^
2 errors
```
I wasn't successful in simplifying this code; the bug fades away when I remove a type argument.

**Comment by jpragey** [comment] 2015-02-04 19:15
After all, maybe it's a dup of #1875 .
Sorry for the inconvenience if it's the case.

**Comment by tombentley** [comment] 2015-02-24 15:04
This is indeed a dupe of #1875, it turns out.

**Closed by tombentley** 2015-02-24 15:04 UTC
Labels: BUG, DUPLICATE
