### ISSUE TITLE
NPE for switch in initializer section

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-compiler#2267] opened 2015-08-09 16:37 UTC
I am getting

compiler bug: null at com.redhat.ceylon.compiler.java.codegen.AbstractTransformer.isJavaEnumType(AbstractTransformer.java:2232)

in the latest dev IDE (Aug 15). An equivalent `if` statement (instead of the switch stmt) did not cause the same problems.

**Comment by tombentley** [comment] 2015-08-18 08:31
@simonthum I'm unable to reproduce this using the following code:

```ceylon
class C(Comparison s) {
    switch(s)
    case (larger) {
        
    }
    else {
        
    }
}
```

in a current version of the IDE. If you're still able to reproduce could you provide a test case please?

**Comment by simonthum** [comment] 2015-08-18 11:57
Not right now but I can add the detail that the switch was not complete (I was trying to discern two interfaces that could be (and should not be prevented from being) implemented at once.

So the `switch`, as opposed to the `if`, was not satisfying definite assignment which might have caused the error. Of course that still should be a better error in that case.

I will revisit tomorrow if that doesn't nail it.

**Comment by tombentley** [comment] 2015-08-18 12:47
I still can't reproduce this.

**Comment by FroMage** [comment] 2015-08-19 13:52
I'm going to close this for now, but please reopen if you can reproduce and give us a test case. Thanks.

**Closed by FroMage** 2015-08-19 13:52 UTC
Labels: BUG, UNREPRODUCIBLE

**Comment by simonthum** [comment] 2015-08-25 18:44
I'm out of luck, not even the original case is reproducible now. Probably it's fixed, whatever it was.
