### ISSUE TITLE
Interop: Unsoundness with "is" test on generic Java types

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2054] opened 2015-02-08 00:42 UTC
Obviously Java objects are not reified, but the compiler lets you act is if they are:

```ceylon
void process<Element>(JList<Element>|{Element*} items)
        given Element satisfies Object {

    print (items is JList<Element>); // always false

    if (is JList<Element> items) {
        // never happens (Util.isReified(...) will never be true)
    }
    else {
        // typechecker and compiler assume {Element*} items, so:
        //      java.lang.ClassCastException: java.util.ArrayList cannot be cast to ceylon.language.Iterable        
    }
}

shared void run() {
    process(JArrayList<String>());
}
```

I guess this is a pretty complicated problem, but it would be nice it were possible to disallow `is` checks like this *unless* the typechecker can guarantee that a simple `instanceof` test is sufficient, which I think it would be in this case.

I can do `is JList<out Anything>`, but that only proves to *me* that I have the right type.

**Comment by jvasileff** [comment] 2015-02-08 00:49
FWIW, the workaround in this case is:

```ceylon
void process<Element>(JList<Element>|{Element*} items)
        given Element satisfies Object {

    print (items is JList<Anything>); // always false

    if (is {Element*} items) {
        
    }
    else {
        // everyone agrees we have JList<Element> here
        print(items.size());
    }
}
```

**Comment by jvasileff** [comment] 2015-02-11 19:09
Could part of a solution for this also be a more general optimization for tests w/reified types?

What I mean is that, in the simple case, when the intersection of the variable's static type and the *most general form* of the desired type satisfies the desired type, why not just skip the `Util.isReified` test, and rely on just `instanceof`?

(By most general form, I mean the the type with the least precise type arguments, e.g. Anything/Nothing. I'm sure there are better words to describe this!)

**Comment by tombentley** [comment] 2015-02-16 15:22
@jvasileff I'm not sure there is a "least precise type argument" to an invariant type parameter.

I'm interested in what @gavinking thinks is the right thing to do here though. It seems to me this is an unintended consequence of the else narrowing feature not playing nicely with interop `is` conditions.

    if (is JList<Element> items) {
        // never happens
    }
    else {
    }

Should we transform the `else` to a `else if (is ElseType) { ... } else {throw}` or something?

**Comment by jvasileff** [comment] 2015-02-16 15:49
> not sure there is a "least precise type argument" to an invariant type parameter.

Good point. Perhaps use site variance, like `HashMap<out Object, out Anything>` would work. I don't know if this idea has legs or not, but I think it would be really nice if it does!

**Comment by gavinking** [comment] 2015-02-16 17:41
I think this is a bug. A runtime exception should occur for cases like this. Indeed, there is an open issue speculating that the typechecker should actually detect this kind of problem at _compile time_.

**Comment by tombentley** [comment] 2015-02-17 09:07
> Indeed, there is an open issue 

Well if there is, I can't find it.

**Comment by jvasileff** [comment] 2015-02-18 06:13
@tombentley, should the original `is` that always returns false throw too?

```ceylon
shared void run() {
    interface Status of Go|Abort {}
    interface Go satisfies Status {}
    interface Abort satisfies Status {}

    // case #1
    JList<out Status> status = JArrayList<Abort>();
    if (!is JList<Abort> status) {
        print ("launch the missles!"); // oops
    }

    // case #2
    JList<String>|JSet<String> collection = JArrayList<String>();
    if (!is JList<String> collection) {
        // ceylon run: java.util.ArrayList cannot be cast to java.util.Set
    }
}
```

**Comment by tombentley** [comment] 2015-02-18 10:00
Ooh, good one.  I didn't think about the possibilities for `!is`. Thanks.

**Comment by FroMage** [comment] 2015-02-18 10:06
The problem is that you can't actually detect if the `is` test will fail until runtime. There are lots of frameworks in Java that use subtyping to implement reified type arguments.

For example:

```java
public static List<Integer> f(){
 return new ArrayList<Integer>(){}; // note the anonymous subtype here
}
```

Then this will actually work at runtime:

```ceylon
 if(is List<Integer> l = f()){}
```

Because the type arguments are _fixed_ in the inheritance graph. Which is why I rejected static analysis to disallow that. This is a common pattern in JEE, including JPA and JAX-RS.

**Comment by quintesse** [comment] 2015-02-18 10:23
@FroMage I'm staring at this for a while now:

```java
public static List<Integer> f(){
 return new ArrayList<Integer>(){}; // note the anonymous subtype here
}
```

And I can't figure out what this is about. Would you be willing to help out a poor sod and explain it to me? :)

**Comment by FroMage** [comment] 2015-02-18 10:29
Java has reified type arguments _only if_ they are fixed in the inheritance tree. For example, if you do `class Foo extends List<Integer>{}` then `List<Integer>` is fixed in the inheritance tree so we can check that instances of `Foo` are indeed instances of `List<Integer>`. That is also the case in anonymous classes which can't be parameterised.

**Comment by tombentley** [comment] 2015-02-18 10:31
@quintesse it's described here http://beust.com/weblog/2011/07/29/erasure-vs-reification/.

@FroMage I wasn't aware that our reified `is` supported this pattern though -- I thought we just used `instanceof` which is only testing raw types.

**Comment by FroMage** [comment] 2015-02-18 10:34
No I don't think we do `instanceof` at all, unless type parameters allow that. And the same test has to work for Ceylon as well it's just regular subtyping without reification.

**Comment by quintesse** [comment] 2015-02-18 10:39
Thanks @FroMage and @tombentley , you learn something new every day :)

**Comment by tombentley** [comment] 2015-02-18 16:12
I'm at a loss to know what the right thing to do here is. With a type like `JList<String>|JList<Integer>` we cannot know which alternative we have at runtime, so for the code:

    if(is JList<String> collection) {
    } else {
    }

I cannot enter *either* block. That's completely counter intuitive. Nor can I throw an exception to say that something completely counter intuitive has happened.

**Comment by gavinking** [comment] 2015-02-18 16:15
Why can't you throw an exception?

**Comment by tombentley** [comment] 2015-02-18 16:22
OK, true, I can generate an `if/else if/else` and throw in the `else` if both tests failed.

**Comment by gavinking** [comment] 2015-02-18 16:29
Well I think you should be more aggressive about it. If one of the tests can't be determined for the given runtime instance, the error should be immediate.

**Comment by FroMage** [comment] 2015-02-18 16:31
Would it make sense to throw in the `is` in certain conditions?

- If the type we're testing for requires reified generics, and
- If the instance we're testing does not support them, and
- If the instance we're testing does not _fix_ reified generics in its inheritance, and
- If the instance we're testing does implement the raw type we're testing for?

That would make reified tests work for Java instances in the following cases:

- It requires no reified generics (true or false)
- It is not even of the tested raw type (false)
- It fixes the reified generics in its inheritance (true or false)

**Comment by tombentley** [comment] 2015-02-19 11:33
I've implemented something along the lines of what @FroMage suggested, but I'm not sure if it's getting some of the more complex cases right.

    // Java (String = j.l.String)
    interface Bug2054Java<T, U extends String> {}
    class Bug2054PartialUpper<U extends String> implements Bug2054Java<String,U> {}
    // Ceylon (JString = j.l.String)
    b = (Bug2054PartialUpper<JString>() of Object) is Bug2054Java<out JString, out JString>;

Now I thought `b` should be true, but to be honest I'm not completely sure.

**Closed** 2015-02-19 11:56 UTC
Labels: BUG

**Comment by FroMage** [comment] 2015-02-19 12:44
In your example, type args are not fixed in inheritance, as they still depend on instance type arguments, so it should throw. In think you can simplify your test a lot by relying on the underlying typechecker model: if you get the non-reified type of the current instance (its `Class`) and ask for the supertype that matches the type you're testing for, and it does not contain open type parameters then they are fixed in inheritance. If the supertype is null that's also an answer. If they contain open type parameters then you throw (if it's not a `ReifiedType` instance).

**Comment by tombentley** [comment] 2015-02-19 16:03
> In your example, type args are not fixed in inheritance, as they still depend on instance type arguments, so it should throw.

Well while that's certainly true in general, in this case we have an upper bound on the type parameter, so even if we don't know the actual type argument we know an upper bound for it, and depending on what question we're asking that extra bit of information might be enough, no? (The question I'm really asking is "what test case do I need to use to prove that `X` is a subtype of `Y` when `X` is only a subtype due to this upper bound constraint).

The algo I've implemented does what you describe already, more or less.

**Comment by FroMage** [comment] 2015-02-20 13:01
The current subtyping algo of the typechecker does not take parameter bounds into account, that's why.

**Comment by gavinking** [comment] 2015-02-20 13:13
You guys have lost me.
