### ISSUE TITLE
compiler fails to build SDK

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-compiler#2295] opened 2015-09-04 17:25 UTC
```
E:\trabalho\ceylon\ceylon-sdk>ant clean publish ide-quick
Buildfile: E:\trabalho\ceylon\ceylon-sdk\build.xml

clean:
   [delete] Deleting directory E:\trabalho\ceylon\ceylon-sdk\modules

compile-jvm:
[ceylon-compile] Note: Created module ceylon.io/1.1.1
[ceylon-compile] Note: Created module ceylon.time/1.1.1
[ceylon-compile] Note: Created module ceylon.process/1.1.1
[ceylon-compile] Note: Created module com.redhat.ceylon.war/1.1.1
[ceylon-compile] Note: Created module ceylon.collection/1.1.1
[ceylon-compile] Note: Created module ceylon.interop.java/1.1.1
[ceylon-compile] Note: Created module ceylon.test/1.1.1
[ceylon-compile] Note: Created module ceylon.math/1.1.1
[ceylon-compile] Note: Created module com.redhat.ceylon.testjvm/1.1.1
[ceylon-compile] Note: Created module com.redhat.ceylon.test/1.1.1
[ceylon-compile] Note: Created module ceylon.net/1.1.1
[ceylon-compile] Note: Created module ceylon.logging/1.1.1
[ceylon-compile] Note: Created module ceylon.dbc/1.1.1
[ceylon-compile] Note: Created module ceylon.html/1.1.1
[ceylon-compile] Note: Created module ceylon.json/1.1.1
[ceylon-compile] Note: Created module ceylon.file/1.1.1
[ceylon-compile] Note: Created module ceylon.locale/1.1.1
[ceylon-compile] Note: Created module ceylon.promise/1.1.1
[ceylon-compile] An exception has occurred in the compiler (ceylonc 1.1.1 (Pif G
adget)).
[ceylon-compile] com.sun.tools.javac.util.Abort: java.io.FileNotFoundException:
C:\Users\DIEGO~1.COR\AppData\Local\Temp\ceylon-compiler-6543388428262755519.car
(O arquivo jß estß sendo usado por outro processo)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1580)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.LanguageCompile
r.close(LanguageCompiler.java:304)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1552)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCom
piler.java:830)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.LanguageCompile
r.compile(LanguageCompiler.java:245)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:650)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:566)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:556)
[ceylon-compile]        at com.redhat.ceylon.compiler.CeylonCompileTool.run(Ceyl
onCompileTool.java:508)
[ceylon-compile]        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonT
ool.java:398)
[ceylon-compile]        at com.redhat.ceylon.common.tools.CeylonTool.execute(Cey
lonTool.java:329)
[ceylon-compile]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[ceylon-compile]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMet
hodAccessorImpl.java:62)
[ceylon-compile]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Deleg
atingMethodAccessorImpl.java:43)
[ceylon-compile]        at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-compile]        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked
(Launcher.java:114)
[ceylon-compile]        at com.redhat.ceylon.ant.CeylonAntTask.executeCommandlin
e(CeylonAntTask.java:229)
[ceylon-compile]        at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAnt
Task.java:186)
[ceylon-compile]        at org.apache.tools.ant.UnknownElement.execute(UnknownEl
ement.java:292)
[ceylon-compile]        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown S
ource)
[ceylon-compile]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Deleg
atingMethodAccessorImpl.java:43)
[ceylon-compile]        at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-compile]        at org.apache.tools.ant.dispatch.DispatchUtils.execute(D
ispatchUtils.java:106)
[ceylon-compile]        at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-compile]        at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-compile]        at org.apache.tools.ant.Target.performTasks(Target.java:
456)
[ceylon-compile]        at org.apache.tools.ant.Project.executeSortedTargets(Pro
ject.java:1393)
[ceylon-compile]        at org.apache.tools.ant.Project.executeTarget(Project.ja
va:1364)
[ceylon-compile]        at org.apache.tools.ant.helper.DefaultExecutor.executeTa
rgets(DefaultExecutor.java:41)
[ceylon-compile]        at org.apache.tools.ant.Project.executeTargets(Project.j
ava:1248)
[ceylon-compile]        at org.apache.tools.ant.Main.runBuild(Main.java:851)
[ceylon-compile]        at org.apache.tools.ant.Main.startAnt(Main.java:235)
[ceylon-compile]        at org.apache.tools.ant.launch.Launcher.run(Launcher.jav
a:280)
[ceylon-compile]        at org.apache.tools.ant.launch.Launcher.main(Launcher.ja
va:109)
[ceylon-compile] Caused by: java.io.FileNotFoundException: C:\Users\DIEGO~1.COR\
AppData\Local\Temp\ceylon-compiler-6543388428262755519.car (O arquivo jß estß se
ndo usado por outro processo)
[ceylon-compile]        at java.io.FileOutputStream.open0(Native Method)
[ceylon-compile]        at java.io.FileOutputStream.open(FileOutputStream.java:2
70)
[ceylon-compile]        at java.io.FileOutputStream.<init>(FileOutputStream.java
:213)
[ceylon-compile]        at java.io.FileOutputStream.<init>(FileOutputStream.java
:162)
[ceylon-compile]        at com.redhat.ceylon.cmr.util.JarUtils.repack(JarUtils.j
ava:125)
[ceylon-compile]        at com.redhat.ceylon.cmr.util.JarUtils.finishUpdatingJar
(JarUtils.java:84)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.JarOutputReposi
toryManager$ProgressiveJar.close(JarOutputRepositoryManager.java:219)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.JarOutputReposi
toryManager.flush(JarOutputRepositoryManager.java:90)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.CeyloncFileMana
ger.flush(CeyloncFileManager.java:221)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1578)
[ceylon-compile]        ... 33 more
[ceylon-compile] ceylon compile: Fatal error: The compiler exited abnormally (4)
 due to a bug in
[ceylon-compile] the compiler.
[ceylon-compile] Please report it:
[ceylon-compile]  https://github.com/ceylon/ceylon-compiler/issues/new
[ceylon-compile] Please include:
[ceylon-compile]
[ceylon-compile] * the stacktrace printed below
[ceylon-compile] * a description of what you were trying to compile.
[ceylon-compile]
[ceylon-compile] Thank you!
[ceylon-compile] com.redhat.ceylon.compiler.CompilerBugException: Bug
[ceylon-compile]        at com.redhat.ceylon.compiler.CeylonCompileTool.handleEx
itCode(CeylonCompileTool.java:527)
[ceylon-compile]        at com.redhat.ceylon.compiler.CeylonCompileTool.run(Ceyl
onCompileTool.java:509)
[ceylon-compile]        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonT
ool.java:398)
[ceylon-compile]        at com.redhat.ceylon.common.tools.CeylonTool.execute(Cey
lonTool.java:329)
[ceylon-compile]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[ceylon-compile]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMet
hodAccessorImpl.java:62)
[ceylon-compile]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Deleg
atingMethodAccessorImpl.java:43)
[ceylon-compile]        at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-compile]        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked
(Launcher.java:114)
[ceylon-compile]        at com.redhat.ceylon.ant.CeylonAntTask.executeCommandlin
e(CeylonAntTask.java:229)
[ceylon-compile]        at com.redhat.ceylon.ant.CeylonAntTask.execute(CeylonAnt
Task.java:186)
[ceylon-compile]        at org.apache.tools.ant.UnknownElement.execute(UnknownEl
ement.java:292)
[ceylon-compile]        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown S
ource)
[ceylon-compile]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Deleg
atingMethodAccessorImpl.java:43)
[ceylon-compile]        at java.lang.reflect.Method.invoke(Method.java:497)
[ceylon-compile]        at org.apache.tools.ant.dispatch.DispatchUtils.execute(D
ispatchUtils.java:106)
[ceylon-compile]        at org.apache.tools.ant.Task.perform(Task.java:348)
[ceylon-compile]        at org.apache.tools.ant.Target.execute(Target.java:435)
[ceylon-compile]        at org.apache.tools.ant.Target.performTasks(Target.java:
456)
[ceylon-compile]        at org.apache.tools.ant.Project.executeSortedTargets(Pro
ject.java:1393)
[ceylon-compile]        at org.apache.tools.ant.Project.executeTarget(Project.ja
va:1364)
[ceylon-compile]        at org.apache.tools.ant.helper.DefaultExecutor.executeTa
rgets(DefaultExecutor.java:41)
[ceylon-compile]        at org.apache.tools.ant.Project.executeTargets(Project.j
ava:1248)
[ceylon-compile]        at org.apache.tools.ant.Main.runBuild(Main.java:851)
[ceylon-compile]        at org.apache.tools.ant.Main.startAnt(Main.java:235)
[ceylon-compile]        at org.apache.tools.ant.launch.Launcher.run(Launcher.jav
a:280)
[ceylon-compile]        at org.apache.tools.ant.launch.Launcher.main(Launcher.ja
va:109)
[ceylon-compile] Caused by: com.sun.tools.javac.util.Abort: java.io.FileNotFound
Exception: C:\Users\DIEGO~1.COR\AppData\Local\Temp\ceylon-compiler-6543388428262
755519.car (O arquivo jß estß sendo usado por outro processo)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1580)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.LanguageCompile
r.close(LanguageCompiler.java:304)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1552)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCom
piler.java:830)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.LanguageCompile
r.compile(LanguageCompiler.java:245)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:650)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:566)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.launcher.Main.compile
(Main.java:556)
[ceylon-compile]        at com.redhat.ceylon.compiler.CeylonCompileTool.run(Ceyl
onCompileTool.java:508)
[ceylon-compile]        ... 25 more
[ceylon-compile] Caused by: java.io.FileNotFoundException: C:\Users\DIEGO~1.COR\
AppData\Local\Temp\ceylon-compiler-6543388428262755519.car (O arquivo jß estß se
ndo usado por outro processo)
[ceylon-compile]        at java.io.FileOutputStream.open0(Native Method)
[ceylon-compile]        at java.io.FileOutputStream.open(FileOutputStream.java:2
70)
[ceylon-compile]        at java.io.FileOutputStream.<init>(FileOutputStream.java
:213)
[ceylon-compile]        at java.io.FileOutputStream.<init>(FileOutputStream.java
:162)
[ceylon-compile]        at com.redhat.ceylon.cmr.util.JarUtils.repack(JarUtils.j
ava:125)
[ceylon-compile]        at com.redhat.ceylon.cmr.util.JarUtils.finishUpdatingJar
(JarUtils.java:84)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.JarOutputReposi
toryManager$ProgressiveJar.close(JarOutputRepositoryManager.java:219)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.JarOutputReposi
toryManager.flush(JarOutputRepositoryManager.java:90)
[ceylon-compile]        at com.redhat.ceylon.compiler.java.tools.CeyloncFileMana
ger.flush(CeyloncFileManager.java:221)
[ceylon-compile]        at com.sun.tools.javac.main.JavaCompiler.close(JavaCompi
ler.java:1578)
[ceylon-compile]        ... 33 more

BUILD FAILED
E:\trabalho\ceylon\ceylon-sdk\build.xml:127: While executing command
   E:\trabalho\ceylon\ceylon-sdk\..\ceylon-dist\dist\bin\ceylon.bat
   compile
   --out
   E:\trabalho\ceylon\ceylon-sdk\modules
   --encoding
   UTF-8
   --source
   E:\trabalho\ceylon\ceylon-sdk\source
   --resource
   E:\trabalho\ceylon\ceylon-sdk\resource
   --pack200
   ceylon.collection
   ceylon.dbc
   ceylon.file
   ceylon.html
   ceylon.interop.java
   ceylon.io
   ceylon.json
   ceylon.logging
   ceylon.math
   ceylon.net
   ceylon.process
   ceylon.promise
   ceylon.test
   ceylon.time
   ceylon.unicode
   ceylon.locale
   com.redhat.ceylon.war
   com.redhat.ceylon.test
   com.redhat.ceylon.testjvm
Compile failed; see the compiler error output for details.

Total time: 1 minute 39 seconds
```

**Comment by quintesse** [comment] 2015-09-04 18:27
Can you try again without having Eclipse running? (Or any other IDE/Editor you might be using)

**Comment by DiegoCoronel** [comment] 2015-09-04 18:47
So, i closed my eclipse, got same error, then i restarted windows and it works now. But i dont know what it means, is it a bug in compiler or my environment ?

**Comment by quintesse** [comment] 2015-09-04 20:13
I doubt it's a bug in the compiler because once it terminates there's no way it can keep anything locked. But any other program that keeps itself in memory can keep files locked on Windows, that's not something we can do anything about.
Next time, instead of exiting Windows, try and find the process that keeps the lock.
(I use [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) for that but surely there are many other/better tools if you google for them)

**Comment by quintesse** [comment] 2015-09-04 20:14
For now I'll close this, but if you can reproduce this you can re-open it.

**Closed by quintesse** 2015-09-04 20:14 UTC
Labels: BUG, UNREPRODUCIBLE

**Comment by FroMage** [comment] 2015-09-04 20:46
Isn't it possible that we lock it to ourselves by opening it twice?

**Comment by sgalles** [comment] 2015-09-04 21:03
FTR I get this too randomly. Here on the compilation of the IDE for instance
https://gist.github.com/sgalles/446d32883f80bfb431c7

**Comment by quintesse** [comment] 2015-09-04 21:28
@sgalles to me that seems another problem, yours says "file not found" instead of "file in use".

@FroMage maybe, but how? We don't do any multi-threading during car generation so wouldn't that mean that we either *always* have the problem or *never*?

**Comment by sgalles** [comment] 2015-09-04 22:03
@quintesse I don't follow, they look very similar to me :

@DiegoCoronel 's error : `Caused by: java.io.FileNotFoundException: C:\Users\DIEGO~1.COR\
AppData\Local\Temp\ceylon-compiler-6543388428262755519.car (O arquivo jß estß se
ndo usado por outro processo)`

My error : `Caused by: java.io.FileNotFoundException: C:\Users\steph\AppData\Local\Temp\ceylon-compiler-5128865962436715346.car (LÆopÚration demandÚe nÆa pu sÆacc
omplir sur un fichier ayant une section mappÚe utilisateur ouverte)`

On the other hand, I admit that the message in French is `operation cannot be performed on a file with a user-mapped section open` and it differs from the message in Portuguese

**Comment by gavinking** [comment] 2015-09-04 22:36
I very often get build failures because I'm in the process of a command line build and Eclipse just happens to get focus, notice changes to the build directory, and starts its own build to compensate.

This might not happen if Eclipse and Ant weren't sharing a build directory.

**Comment by quintesse** [comment] 2015-09-04 23:41
@sgalles no, you're right, they *do* seem pretty similar after all

**Comment by sgalles** [comment] 2015-09-16 20:45
OK, I have an information about this, I don't know if its useful, so it is totally FYI :
Using https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx I could find out that during the compilation the temporary file `ceylon-compiler-xxxxxxxxxx.car` is opened twice by the compiler.

For instance :
During the compilation we have :
`java.exe           pid: 3464   type: File           37C: C:\Users\admin\AppData\Local\Temp\ceylon-compiler-234598420650129219.car` 

then a few seconds later
`java.exe           pid: 3464   type: File           384: C:\Users\admin\AppData\Local\Temp\ceylon-compiler-234598420650129219.car`

`37C` and `384` are the file handles. So, maybe something goes wrong at some point if there was an overlap between the two operation. I don't know.

**Comment by quintesse** [comment] 2015-09-16 21:36
Well several file handles doesn't surprise me, we're dealing with a temporary files after all, so we have to rename it / copy it to its final destination. Overlap would not be impossible of course, but when dealing with a single-threaded application I would think it would be much easier to reproduce.

**Comment by sgalles** [comment] 2015-09-16 22:30
Well, it's pure speculation on my part but I've already experienced something like this with a single-threaded application : 
a java object is not closed but is not referenced anymore, then the GC kicks in, and a finalyzer closes the handle *most of the time*. 
But when the GC does not kick in soon enough you get a failure randomly if you try to open the same handle once again.
