### ISSUE TITLE
StackOverflowError when generating language module apidoc

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2158] opened 2015-05-13 11:21 UTC
This could belong in `ceylon-spec`, but I'll report it here because it seems vaguely `ceylon doc`-related.

```
generate-apidoc:
     [exec] Exception in thread "main" java.lang.StackOverflowError
     [exec] 	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
     [exec] 	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
     [exec] 	at java.io.File.exists(File.java:819)
     [exec] 	at java.io.File.mkdirs(File.java:1340)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getOutputFolder(CeylonDocTool.java:532)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getApiOutputFolder(CeylonDocTool.java:519)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getFolder(CeylonDocTool.java:508)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getObjectFile(CeylonDocTool.java:548)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getAbsoluteObjectUrl(CeylonDocTool.java:1044)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getObjectUrl(CeylonDocTool.java:1106)
     [exec] 	at com.redhat.ceylon.ceylondoc.CeylonDocTool.getObjectUrl(CeylonDocTool.java:1101)
     [exec] 	at com.redhat.ceylon.ceylondoc.LinkRenderer.getLocalUrl(LinkRenderer.java:644)
     [exec] 	at com.redhat.ceylon.ceylondoc.LinkRenderer.getUrl(LinkRenderer.java:617)
     [exec] 	at com.redhat.ceylon.ceylondoc.LinkRenderer.access$100(LinkRenderer.java:75)
     [exec] 	at com.redhat.ceylon.ceylondoc.LinkRenderer$1.getSimpleDeclarationName(LinkRenderer.java:101)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.printDeclaration(ProducedTypeNamePrinter.java:595)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getSimpleProducedTypeName(ProducedTypeNamePrinter.java:529)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:268)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:236)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:261)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getSimpleProducedTypeName(ProducedTypeNamePrinter.java:557)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:268)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:236)
     [exec] 	at com.redhat.ceylon.model.typechecker.util.ProducedTypeNamePrinter.getProducedTypeName(ProducedTypeNamePrinter.java:261)

```

**Comment by FroMage** [comment] 2015-06-03 13:52
I can't reproduce. Also, this is tested in the ceylondoc tests. Can you reproduce?

**Comment by FroMage** [comment] 2015-06-04 12:34
I'm going to close this. Reopen if you can reproduce.

**Closed by FroMage** 2015-06-04 12:34 UTC
Labels: BUG, IN PROGRESS
