### ISSUE TITLE
Compiler error with generic inner classes

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-compiler#2118] opened 2015-04-08 10:41 UTC
The following code:

```ceylon
shared interface Observer<T> { }

shared interface Observable<T> {
    
    shared default Observable<U> lift<U>() {
        return object satisfies Observable<U> { };
    }
    
    shared class FunctionsObserver<U>() satisfies Observer<U> { }
}
```

results in this compiler error:

```
error: anonymous_0_ is not abstract and does not override abstract method <U#1>FunctionsObserver$new$(TypeDescriptor) in Observable
  where U#1,T,U#2 are type-variables:
    U#1 extends Object declared in method <U#1>FunctionsObserver$new$(TypeDescriptor)
    T extends Object declared in interface Observable
    U#2 extends Object declared in method <U#2>lift(TypeDescriptor)
```

if you change the `FunctionsObserver` type parameter's name from `U` to something else, say:

```ceylon
shared class FunctionsObserver<V>() satisfies Observer<V> { }
```

you'll get a very nasty:

```
com.redhat.ceylon.compiler.CompilerBugException: Bug
	at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:519)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:501)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:50)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:30)
Caused by: java.lang.RuntimeException: Error generating bytecode for ./source/hello/test.ceylon
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:785)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCode(LanguageCompiler.java:725)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1450)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.generate(LanguageCompiler.java:836)
	at com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1418)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:230)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
	at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:500)
	... 16 more
Caused by: java.lang.AssertionError: typeSig 19
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:367)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:413)
	at com.sun.tools.javac.jvm.ClassWriter.assembleClassSig(ClassWriter.java:405)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:310)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:323)
	at com.sun.tools.javac.jvm.ClassWriter.assembleSig(ClassWriter.java:358)
	at com.sun.tools.javac.jvm.ClassWriter.typeSig(ClassWriter.java:438)
	at com.sun.tools.javac.jvm.ClassWriter.writeMemberAttrs(ClassWriter.java:717)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethod(ClassWriter.java:1032)
	at com.sun.tools.javac.jvm.ClassWriter.writeMethods(ClassWriter.java:1496)
	at com.sun.tools.javac.jvm.ClassWriter.writeClassFile(ClassWriter.java:1579)
	at com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1514)
	at com.redhat.ceylon.compiler.java.codegen.CeylonClassWriter.writeClass(CeylonClassWriter.java:63)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.genCodeUnlessError(LanguageCompiler.java:775)
	... 27 more
```

The problems go away the moment you make the inner class non-shared.

**Comment by quintesse** [comment] 2015-04-08 10:43
The generated code in the first case is:

```java
public interface Observer<T> {
}
public interface Observable<T> {
    
    public .hello.Observable$impl<T> $hello$Observable$impl();
    
    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U);
    
    public <U>.hello.Observable$impl<T>.FunctionsObserver<U> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U);
}
public final class Observable$impl<T> {
    
    public Observable$impl(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T, .hello.Observable<T> $this) {
        this.$reified$T = $reified$T;
        this.$this = $this;
    }
    private .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T;
    private final .hello.Observable<T> $this;
    
    public void $refine$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T) {
        this.$reified$T = $reified$T;
    }
    
    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
        return (
            let
            {
                
                class anonymous_0_ implements .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType, .hello.Observable<U> {
                    
                    private anonymous_0_() {
                        this.$hello$Observable$this$ = new .hello.Observable$impl<U>($reified$U, this);
                    }
                    protected final .hello.Observable$impl<U> $hello$Observable$this$;
                    
                    @.java.lang.Override
                    public .hello.Observable$impl<U> $hello$Observable$impl() {
                        return $hello$Observable$this$;
                    }
                    
                    @.java.lang.Override
                    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
                        return $hello$Observable$this$.lift($reified$U);
                    }
                    
                    @.java.lang.Override
                    public final <U>.hello.Observable$impl<U>.FunctionsObserver<(ERROR)> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
                        return $hello$Observable$this$.FunctionsObserver$new$($reified$U);
                    }
                    
                    @.java.lang.Override
                    public .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $getType$() {
                        return .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable.class, .hello.Observable$impl.this.$reified$T), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.functionOrValue("lift", $reified$U)), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(anonymous_0_.class));
                    }
                }
            }
            returning new anonymous_0_();
        );
    }
    
    public <U>.hello.Observable$impl<T>.FunctionsObserver<U> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
        return new FunctionsObserver<U>($reified$U);
    }
    
    public class FunctionsObserver<U> implements .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType, .hello.Observer<U> {
        
        protected FunctionsObserver(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
            this.$reified$U = $reified$U;
        }
        private final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U;
        
        @.java.lang.Override
        public .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $getType$() {
            return .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable.class, .hello.Observable$impl.this.$reified$T), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable$impl.FunctionsObserver.class, $reified$U));
        }
    }
}
```

**Comment by quintesse** [comment] 2015-04-08 10:45
In the second case its:

```java
public interface Observer<T> {
}
public interface Observable<T> {
    
    public .hello.Observable$impl<T> $hello$Observable$impl();
    
    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U);
    
    public <V>.hello.Observable$impl<T>.FunctionsObserver<V> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$V);
}
public final class Observable$impl<T> {
    
    public Observable$impl(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T, .hello.Observable<T> $this) {
        this.$reified$T = $reified$T;
        this.$this = $this;
    }
    private .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T;
    private final .hello.Observable<T> $this;
    
    public void $refine$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$T) {
        this.$reified$T = $reified$T;
    }
    
    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
        return (
            let
            {
                
                class anonymous_0_ implements .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType, .hello.Observable<U> {
                    
                    private anonymous_0_() {
                        this.$hello$Observable$this$ = new .hello.Observable$impl<U>($reified$U, this);
                    }
                    protected final .hello.Observable$impl<U> $hello$Observable$this$;
                    
                    @.java.lang.Override
                    public .hello.Observable$impl<U> $hello$Observable$impl() {
                        return $hello$Observable$this$;
                    }
                    
                    @.java.lang.Override
                    public <U>.hello.Observable<U> lift(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$U) {
                        return $hello$Observable$this$.lift($reified$U);
                    }
                    
                    @.java.lang.Override
                    public final <V>.hello.Observable$impl<U>.FunctionsObserver<(ERROR)> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$V) {
                        return $hello$Observable$this$.FunctionsObserver$new$($reified$V);
                    }
                    
                    @.java.lang.Override
                    public .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $getType$() {
                        return .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable.class, .hello.Observable$impl.this.$reified$T), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.functionOrValue("lift", $reified$U)), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(anonymous_0_.class));
                    }
                }
            }
            returning new anonymous_0_();
        );
    }
    
    public <V>.hello.Observable$impl<T>.FunctionsObserver<V> FunctionsObserver$new$(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$V) {
        return new FunctionsObserver<V>($reified$V);
    }
    
    public class FunctionsObserver<V> implements .com.redhat.ceylon.compiler.java.runtime.model.ReifiedType, .hello.Observer<V> {
        
        protected FunctionsObserver(final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$V) {
            this.$reified$V = $reified$V;
        }
        private final .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $reified$V;
        
        @.java.lang.Override
        public .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor $getType$() {
            return .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.member(.com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable.class, .hello.Observable$impl.this.$reified$T), .com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.klass(.hello.Observable$impl.FunctionsObserver.class, $reified$V));
        }
    }
}
```

**Comment by tombentley** [comment] 2015-04-08 13:33
The first problem is basically the same as https://github.com/ceylon/ceylon-compiler/issues/2072.

**Comment by tombentley** [comment] 2015-04-08 13:53
The second problem is now fixed. I'm going to close this, since it's now essentially a dupe of #2072.

**Closed by tombentley** 2015-04-08 13:53 UTC
Labels: BUG, high priority
