### ISSUE TITLE
Type inference problem with {element+} and inline if/else

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon-compiler#2150] opened 2015-05-04 01:07 UTC
As discussed in https://groups.google.com/forum/#!msg/ceylon-users/LPlNjl_FI-I/49TDijdRC04J

This code used to work:
```ceylon
        Boolean hasContent = {
            if (is ContainedMarkup markup,
                markup.containedContent != "") true}.first else false;
```

It now gives a backend error:

```
incompatible types
  required: ceylon.language.Boolean
  found:    java.lang.Object
```

**Comment by gavinking** [comment] 2015-05-04 09:48
@akberc do you have a self-contained example to reproduce this?

**Comment by lucaswerkmeister** [comment] 2015-05-04 15:02
@gavinking:
```ceylon
Boolean b = { if (true) true }.first else false;
```
As always, [generated code](https://gist.github.com/lucaswerkmeister/75b9f99f34d1575fda62), `@noanno`’d ;-)

**Comment by lucaswerkmeister** [comment] 2015-05-04 15:07
> ```java
> c.l.Boolean $ceylontmp$0 = new c.r.c.c.j.l.LazyIterable<c.l.Boolean, j.l.Object>(…){…}.getFirst();
> ```

I assume `getFirst` returns `j.l.Object` in Java?

**Comment by akberc** [comment] 2015-05-04 16:05
Thank you @lucaswerkmeister 

It appears that the issue may be limited.  In this case it is with Boolean, where Java Boolean and Ceylon Boolean are getting confused, and since the Iterable.next() is Object, it is not cast properly.

With String, this compiles fine, as the cast is to `ceylon.language.String`:
```ceylon
	String s = { if (true) "s" }.first else "s";
```

**Comment by FroMage** [comment] 2015-06-04 10:02
Mmm, this is due to `Tree.DefaultOp` having type `false|true` instead of `Boolean`. @gavinking is this normal?

**Comment by gavinking** [comment] 2015-06-04 10:13
@FroMage yeah, it's correct. We don't strip away the anonymous class types anymore _except_ right at the end when you assign to a `value` or `function`, for example:

```ceylon
value hasContent = (1==1 then true) else false;
```

Here `hasContent` gets the inferred type `Boolean`, but the expression itself has the more precise type `true|false`.

This was a change that happened a few months ago, when we introduced `\Itrue`, etc.

**Comment by gavinking** [comment] 2015-06-04 10:16
@FroMage you might need to get a bit more aggressive about calling `Unit.denotableType()`. I guess the typechecker used to do it for you in some places where it no longer does.

**Comment by FroMage** [comment] 2015-06-04 10:20
OK, I made our test more lenient and it seems to be enough. Thanks.

**Comment by lucaswerkmeister** [comment] 2015-06-04 16:47
The issue isn’t restricted to `ceylon.language::Boolean`:
```ceylon
abstract class MyBoolean() of myTrue | myFalse {}
object myTrue extends MyBoolean() {}
object myFalse extends MyBoolean() {}
MyBoolean mb = { if (true) myTrue }.first else myFalse; // error: required MyBoolean, found Object

Comparison c = { if (true) smaller}.first else larger; // error: required Comparison, found Object
```

**Comment by FroMage** [comment] 2015-06-04 17:26
OK thanks, I know how to fix this.

**Comment by FroMage** [comment] 2015-07-06 15:36
Done again.

**Closed** 2015-07-06 15:35 UTC
Labels: BUG, IN PROGRESS

**Comment by lucaswerkmeister** [comment] 2015-07-06 15:39
Thanks!
