### ISSUE TITLE
Interop error with Java Interface that defines setter only

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2020] opened 2015-01-27 21:45 UTC
With a Java Interface that defines *just* a setter:

```java
public interface PropSetter {
    void setProp(String value);
}
```

and a class that adds a getter:

```java
public class JavaBean implements PropSetter {

    private String prop;

    public String getProp() {
        return prop;
    }

    @Override
    public void setProp(String prop) {
        this.prop = prop;
    }
}
```

There is an error attempting to extend the class in Ceylon:

```ceylon
class JB() extends JavaBean() {} // error
// Formal member setProp of PropSetter not implemented in class hierarchy
```

**Comment by jvasileff** [comment] 2015-01-27 21:51
I'm not sure what the workaround would be for this one - the `JavaBean.setProp` seams to completely disappear:

```ceylon
class JB() extends JavaBean() {
    shared actual void setProp(String string) {
        super.setProp(string); // error
        // Supertype member is declared formal: setProp of PropSetter
    }
}
```

**Comment by gavinking** [comment] 2015-01-27 22:00
Man, that's _sooo_ crazy.... :(

**Comment by tombentley** [comment] 2015-01-28 11:45
@jvasileff the work around is

    shared actual void setProp(String string) {
        super.prop = string; 
    }

because Ceylon sees both a method and a variable attribute.

**Comment by jvasileff** [comment] 2015-02-01 17:01
> the work around is

Ok, thanks. That usually works. But sometimes, the setter is final in the parent class!

**Comment by tombentley** [comment] 2015-02-02 16:03
I think that this would be addressed by #1234, so unless @jvasileff can show that this issue affects some super-commonly used library or framework I proposed we defer this to 1.3 like we have #1234

**Comment by jvasileff** [comment] 2015-02-02 16:25
It's prevalent in Spring. Beyond that, I'm not sure.

The idea is that before everyone moved to annotations, there were interfaces you could implement to ask for certain injections (or I think even things like event notifications.) For example, the interface `ApplicationContextAware` has only one method, `setApplicationContext`. Unfortunately, useful or even necessary abstract implementations of these interfaces sometimes mark the setter as `final`.

**Comment by jvasileff** [comment] 2015-02-02 16:31
I'll add that this hasn't been a major issue for me yet, but it could become one.

The worst case I've seen so far was in adding support for `ceylon.html` for views, and my workaround was to forgo a convenience abstract class and just implement the necessary interface directly.

**Comment by tombentley** [comment] 2015-02-02 17:23
OK thanks, that's useful context.

**Comment by jvasileff** [comment] 2015-02-02 17:26
Looks like this is a dup of #1368

**Comment by tombentley** [comment] 2015-02-26 10:24
This is indeed a dupe of #1368, so I'm going to close this. Note: unfortunately #1368 is currently for 1.3 :-(

**Closed by tombentley** 2015-02-26 10:24 UTC
Labels: DUPLICATE

**Comment by jvasileff** [comment] 2015-02-26 18:25
Ok, thanks for the update @tombentley. What's impressive is how many features and issues you guys *have* addressed in this release!
