### ISSUE TITLE
Regression: Type of generic argument seems to be lost when it is part of a type-union

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-compiler#2412] opened 2015-11-01 21:19 UTC
The following code works in Ceylon 1.1 but not in 1.2:

```ceylon
shared void expect<Expected>(
    Anything actual,
    Type<Expected>|Anything(Expected) \ithen) {
    if (is Expected actual) {
        if (is Anything(Expected) \ithen) {
            \ithen(actual);
        }
    } else {
        fail("Expected `` type(`Expected`) `` but was ``type(actual)``");
    }
}

shared void runMe() {
	expect("", `String`);
	expect("", (String s) => s);
}
```

Removing the union in the second argument of `expect` so that its type is just `Anything(Expected)` makes it  work fine for the second test.

**Comment by renatoathaydes** [comment] 2015-11-01 21:21
The error message is:

```
Exception in thread "main" ceylon.language.AssertionError 
"Expected ceylon.language.meta.model::nothingType 
  but was ceylon.language::String"
```

**Comment by jvasileff** [comment] 2015-11-01 21:51
Tricky. I *think* this isn't really solvable.

For `Type<Expected>`, `Expected` is covariant. For `Anything(Expected)`, `Expected` is contravariant. So, per the rules, it is treated as covariant by default. With intuition, we know if we want a covariant or contravariant interpretation based on whether we're passing in a `Type` or a `Callable`, but I'm not sure the type checker can figure that out. Hardcoding one or the other isn't an option, which one we want depends on the runtime argument type. Further complicating things in this example, `` `String` `` is actually both a `Type` and a `Callable`.

Some notes:
```ceylon
    // covariant idea of `Expected` is `String`
    Type<String> arg1 = `String`;

    // contravariant idea of `Expected` is `{Character*}`
    Anything({Character*}) arg2 = `String`;

    // covariant idea of `Expected` is `Nothing`
    // contravariant idea of `Expected` is `String`
    Anything(String) arg3 = (String s) => s;
```

You can also experiment with an explicit type hint:

```
shared void expect<in Expected>(
```

or removing `Type<Expected>` from the union, making the parameter type just `Anything(Expected)`.

**Comment by lucaswerkmeister** [comment] 2015-11-01 21:58
@jvasileff so you’re saying this is an unfortunate result of the deliberate change to function type parameter variance inference in ceylon/ceylon-spec#1302?

**Comment by jvasileff** [comment] 2015-11-01 22:00
Yes, except I'm not sure I agree with the "unfortunate" qualifier, in a strict technical sense (I do of course wish @renatoathaydes code worked.)

**Comment by jvasileff** [comment] 2015-11-01 23:07
BTW, I think the way type inference is used in the example isn't quite correct. The goal seems to be to test if the argument `actual` is a subtype of the passed-in `Type<> \ithen`, and *not* whether it is a subtype of the *inferred* argument `Expected`. (If `Type` were invariant, this might be easier.)

This could be written like this (probably with room for improvement):

```ceylon
Boolean tryCall<T>(T arg, Anything(Nothing) f) {
    if (is Anything(T) f) {
        f(arg);
        return true;
    }
    return false;
}

shared void expect(
        Anything actual,
        Type<Anything> | Anything(Nothing) \ithen) {

    value actualType = type(actual);

    if (is Type<Anything> \ithen,
            ! actualType.subtypeOf(\ithen)) {
        throw Exception("Expected ``\ithen`` but was ``actualType``");
    }
    if (is Anything(Nothing) \ithen) {
        assert (is Boolean called = `function tryCall`.invoke([actualType], actual, \ithen));
        print("Called = " + called.string);
    }
}

shared void runMe() {
    expect("", `String`);
    expect("", (String s) => s);
}
```

or with type inference *just* for the possible function:

```ceylon
shared void expect<Expected>(
        Anything actual,
        Type<Anything> | Anything(Expected) \ithen) {

    value actualType = type(actual);

    if (is Type<Anything> \ithen,
            ! actualType.subtypeOf(\ithen)) {
        throw Exception("Expected ``\ithen`` but was ``actualType``");
    }
    else if (is Anything(Expected) \ithen) {
        if (is Expected actual) {
            \ithen(actual);
        }
        else {
            throw Exception("Function not suitable for passed in value");
        }
    }
}

shared void runMe() {
    expect("", `String`);
    expect("", (String s) => s);
}
```

or, in a way that avoids the use of `Type`, and requires the caller to explicitly specify `Expected`. But this would likely result in bugs.

```ceylon
shared void expect<Expected>(
        Anything actual,
        Anything(Expected) \ithen = noop) {

    if (is Expected actual) {
        \ithen(actual);
    } else {
        throw Exception("Expected `` type(`Expected`) `` but was ``type(actual)``");
    }
}

shared void runMe() {
    expect<String>("");
    expect("", (String s) => s);
}
```

These might need to be adjusted to match exactly the type of error handling/validation that is required.

**Comment by gavinking** [comment] 2015-11-02 00:00
Yes, it's clearly an issue introduced by the new type argument variance inference algorithm: the occurrence of `Expected` in the union type forces the typechecker to treat it `Expected` as covariant, as @jvasileff has observed.

The code can be made to compile by explicitly annotating `Expected` as contravariant, i.e.

```ceylon
shared void expect<in Expected>(
    Anything actual,
    Anything(Expected)|Type<Expected> t) {
    if (is Expected actual) {
        if (is Anything(Expected) t) {
            t(actual);
        }
    } else {
        print("Expected `` type(`Expected`) `` but was ``type(actual)``");
    }
}

shared void runMe() {
    expect("", `String`);
    expect("", (String s) => s);
}
```

This is an acceptable solution to me, and so I'm inclined to close the issue. WDYT?

**Comment by jvasileff** [comment] 2015-11-02 00:20
@gavinking I think @renatoathaydes should look to one of my examples as a solution to his problem.

Testing `actual` against the inferred type parameter of `Type` can result in senseless things, like tests against `Anything` or the type of `Expected`'s initialization parameter, rather than the type represented by `Type` itself.

**Comment by renatoathaydes** [comment] 2015-11-02 07:55
Thanks guys for pointing out the root of the problem and alternative solutions.

However, I would have expected the type argument to be treated as invariant in this example and I cannot see why it should be otherwise. It is used as covariant by one argument, as contra-variant by the other argument, seems clear to me the only compromise to make is to call it invariant?

If I'm wrong above, then I accept this is definitely **unfortunate** and surprising behaviour which makes the language harder to use.

**Comment by renatoathaydes** [comment] 2015-11-02 08:08
> Testing actual against the inferred type parameter of Type can result in senseless things, like tests against Anything or the type of Expected's initialization parameter, rather than the type represented by the instance \ithen of Type itself.

Sure, but your suggestions actually make the problem worse.

Using `Anything` as a type in the function allows me to write all sorts of non-sense:

```ceylon
expect(true, `String`);
expect("", (Boolean b) => b);
```

Just as I cannot do `String s = ""; if (is Boolean s) {}`, I don't want to be able to do the above, hence the type parameter, which worked fine in Ceylon 1.1 and I hoped would work fine in 1.2. But given that inferred-type is the root of the problem, I will just add an `in` to the type parameter and test if the behaviour is as expected for all use-cases I have.

BTW: this function tests that the argument is either of a type `Expected` or calls the given function when it is. This allows me to make assertions on a variable only if the type is as expected, and throw in case it isn't.

There might be better ways to do this, and I will consider using something like Kotlin's `let`, which I think can be written trivially in Ceylon (need to get back home to try these).

**Comment by renatoathaydes** [comment] 2015-11-02 08:12
> Using Anything as a type in the function allows me to write all sorts of non-sense:

Ops, looks like I can write the non-sense code with pretty much all alternatives, including my own old version... Sorry @jvasileff for making a stupid remark.

**Comment by FroMage** [comment] 2015-11-02 11:17
Guys, this is a spec/typechecker issue, right?

**Comment by gavinking** [comment] 2015-11-02 12:17
@renatoathaydes well we designed the new rules for variance inference knowing that they would not cover _every_ case since the problem is fundamentally ambiguous. We can make the rules more and more complex and maybe make some additional cases work, but we would also be breaking other cases. Ultimately the user is going to have to explicitly disambiguate some of the time. With the new rules they have to do it less often than before.

**Comment by gavinking** [comment] 2015-11-02 12:17
@FroMage yes, closing.

**Closed by gavinking** 2015-11-02 12:17 UTC
Labels: BUG

**Comment by renatoathaydes** [comment] 2015-11-02 20:18
I agree my case was an edge-case and that's fine.

I didn't need the function to look like that to do what I needed, I think ended up coming to a better design in the end.

Here's what it looks like now:

```ceylon
shared class TypeAssertion<out Expected>(Anything instance, Type<Expected> expectedType) {
	// gives a good  error message
	assertEquals(type(instance), `Expected`,
		"Result does not have the expected type");
	
	// narrow the type
	assert (is Expected instance);
	
	shared void with(void assertions(Expected expected)) {
		assertions(instance);
	}
}

shared class AssertionMaker<Ex>(Ex instance) {
	
	shared TypeAssertion<Expected> ofType<Expected>(Type<Expected> expectedType)
		=> TypeAssertion(instance, expectedType);
	
}

shared AssertionMaker<Ex> expect<Ex>(Ex actual) => AssertionMaker(actual);
```

Which I use like this:

```ceylon
    expect(parser.parse("")).ofType(`ParseSuccess<[]>`).with((result) {
        // result is an instance of ParseSuccess<[]> here!
        assertEquals(result.result.sequence(), []);
    });
```

Just a silly example, but it shows what I was doing.... with the code above, if something goes wrong and the parser fails, I get this message:

```ceylon
ceylon.test.AssertionComparisonError "Result does not have the expected type:
expected <com.athaydes.parcey::ParseSuccess<ceylon.language::Empty>> 
but was <com.athaydes.parcey::ParseError>"
```

Which is much better than Ceylon's native assert:

```ceylon
ceylon.language.AssertionError "Assertion failed
	violated is Expected instance"
```
