### ISSUE TITLE
Usage warning in ceylon help

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2105] opened 2015-03-23 11:48 UTC
```
$ ceylon help >&-
ceylon: Unrecognised long option '--_print-summary' to command 'ceylon'

Usage:
ceylon [--stacktraces] [--version] [--] [<tool-arguments...>]

Run 'ceylon help' for more help
```
I think [`ceylon-sh-setup`](https://github.com/ceylon/ceylon-compiler/blob/master/bin/ceylon-sh-setup) is supposed to handle that, but it doesn’t seem to be sourced… anywhere.

Not sure if this actually belongs in this repository…

**Comment by quintesse** [comment] 2015-03-23 12:08
And you only get this when running `ceylon help >&-` ? Or does simply running `ceylon help` cause the same error?

**Comment by lucaswerkmeister** [comment] 2015-03-23 12:09
`ceylon help` does the same thing, it’s just not visible until you close the pager.

**Comment by quintesse** [comment] 2015-03-23 12:11
Updating to latest of master to see if I can reproduce this because right now I can't.

**Comment by lucaswerkmeister** [comment] 2015-03-23 12:12
I’ll update too, but I seem to remember this from at least a few days ago.

**Comment by quintesse** [comment] 2015-03-23 12:15
It might have unknowingly fixed this in the stuff I've still got to merge.

**Comment by quintesse** [comment] 2015-03-31 10:11
@lucaswerkmeister , now that I pushed all my stuff could you check if the problem went away for you?

**Comment by lucaswerkmeister** [comment] 2015-03-31 12:36
I still get the same results here.

**Comment by lucaswerkmeister** [comment] 2015-03-31 12:56
Weird, no such output on the server. Seems like a problem on my local setup.

**Comment by quintesse** [comment] 2015-03-31 13:09
Do you perhaps have any non-standard `ceylon-xxxx.sh` plugin scripts in your environment?

**Comment by lucaswerkmeister** [comment] 2015-03-31 13:09
the formatter script perhaps?

**Comment by quintesse** [comment] 2015-03-31 13:11
Well I consider that one pretty standard already heh
No, maybe some experiment you did with weird naming or something like that.
It's almost as if in your case it gets confused and thinks "ceylon" itself is a shell plugin script.

**Comment by quintesse** [comment] 2015-03-31 23:12
Can anyone else reproduce this? @FroMage @davidfestal @chochos ?

**Comment by chochos** [comment] 2015-04-01 03:55
nope... nothing happens with the `>&-` and no error shows up with plain `ceylon help`

**Comment by quintesse** [comment] 2015-04-01 08:07
Thanks @chochos . So I'm going to close this, if you can find a way to reproduce this somewhere else besides your local system you can reopen this issue again @lucaswerkmeister

**Closed by quintesse** 2015-04-01 08:07 UTC
Labels: BUG, UNREPRODUCIBLE
