### ISSUE TITLE
Compiler bug when trying to compile ceylon.ast

### ISSUE THREAD

**Issue by Gurkenmaster** [ceylon/ceylon-compiler#2352] opened 2015-10-12 14:29 UTC
When I try to compile ceylon.ast I keep getting this error. 
```[ceylon-compile] /home/bergelmir/ceylon/ceylon.ast/source/ceylon/ast/core/UnionType.ceylon:31: error: incompatible types
[ceylon-compile]     shared UnionType copy([<IntersectionType|PrimaryType>+] children = this.children) {
[ceylon-compile]                                                                        ^
[ceylon-compile]   required: Sequence
[ceylon-compile]   found:    Sequential```

I took a closer look at the UnionType.ceylon file I couldn't find anything wrong with it.
https://github.com/ceylon/ceylon.ast/blob/master/source/ceylon/ast/core/UnionType.ceylon#L31

**Comment by lucaswerkmeister** [comment] 2015-10-12 15:06
Dupe of #2179, which I *still* haven’t added a workaround for in the vain hope that it’ll get fixed in time for 1.2 (even though the issue was moved to 1.3 because it’s “hard to fix and hard to find” – @FroMage should remember that!).

@Gurkenmaster: You can just ignore the error. The compiler still produces a `.car`, so as long as you don’t actually call the method, you’re good.

I guess I should add a workaround for the 1.2 release though.

**Comment by FroMage** [comment] 2015-10-12 15:10
Oh yes please if it's the same thing can you work around it in your code? Seeing an error is scary ;)

**Closed by FroMage** 2015-10-12 15:10 UTC
Labels: BUG

**Comment by lucaswerkmeister** [comment] 2015-10-12 18:48
Actually… I can’t reproduce this right now.

**Comment by jvasileff** [comment] 2015-10-12 18:52
Reproduce with:

    ceylon compile ceylon.ast.core source/ceylon/ast/core/UnionType.ceylon

**Comment by lucaswerkmeister** [comment] 2015-10-12 18:53
thanks @jvasileff, that works, even though I still don’t get the error with just `ceylon compile ceylon.ast.core`.

**Comment by jvasileff** [comment] 2015-10-12 18:55
Right, same here - https://github.com/ceylon/ceylon-compiler/issues/2179#issuecomment-114673927

But the IDE compiler might specify the file.

**Comment by lucaswerkmeister** [comment] 2015-10-12 18:56
Oh, right, I forgot about that.

**Comment by lucaswerkmeister** [comment] 2015-10-12 19:33
Alright, workaround pushed.
