### ISSUE TITLE
default native declarations added in reverse order

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2371] opened 2015-10-19 06:50 UTC
The output for the program below should be `{ 1, 2 }`, but is `{ 2, 1 }`:

```ceylon
native class NC7() {
    native shared variable Integer i = 0;
    native shared Integer j = ++i;
    native shared Integer k = ++i;
}

native("jvm") class NC7() {}
native("js") class NC7() {}

shared void testNC7() {
    value nc7 = NC7();
    print({nc7.j, nc7.k});
}
```

The problem appears to be `NativeUtil.mergeStatements()` reversing the order as it adds to the `LinkedList` result.

FWIW, a variation:

```ceylon
native class NC7() {
    native shared variable Integer i = 0;
    native shared Integer j = ++i;
    native shared Integer k = ++i;
}

native("jvm") class NC7() {
    native("jvm") shared variable Integer i = 10;
}

shared void testNC7() {
    value nc7 = NC7();
    print({nc7.i, nc7.j, nc7.k});
}
```
prints `{ 10, 2, 1 }`.

Removing `shared` from `native shared variable Integer i` in the first example results in backend errors.

**Comment by quintesse** [comment] 2015-10-19 14:21
Can anybody confirm my suspicion that the problem explained in this issue basically means that the members defined in a native implementation must always appear in the exact same order as in the native header? (@gavinking?)

I mean of course there's no problem in writing this:

```ceylon
native shared class X() {
    native Integer one;
    native Integer two;
}
native("jvm") shared class X() {
    native Integer one => 1;
    native Integer two = 2;
}
```

but the problem is that I see no (easy) way of detecting when and which members are "order insensitive" and which need to maintain the same order

Also, once you go there how do you explain (for larger classes) to the user that members a, b, c and d must be in the same order as in the header but that e, f, g and h can be in any order you want?
Still, it seems very heavy-handed to have to say "all members must be in the same order!!"

(the other option would be to not allow default implementations in the header at all but it's something that was actually already in use in the language module before the new native system with backends was created, so that might not really be an option either)

**Comment by quintesse** [comment] 2015-10-19 14:44
Btw, I already implemented a restriction on the use of (non-declaration) statements in native headers because I don't think there's a sane way to handle the merging of the statements of a native class and its implementation.

But @jvasileff suggested on Gitter that adding a restriction on eagerly evaluated values could help but he thought it might not be enough.

Are there some restrictions we can come up with for declarations in native headers that would remove the need for an excessively heavy-handled rule that says that all declarations must appear in the same order? (I already implemented this restriction locally btw, and it does work)

**Comment by jvasileff** [comment] 2015-10-19 14:45
I was trying to work through if it would be ok to just prohibit eager values, but this seems to be a problem:

```ceylon
shared native class ClassA() {
    native shared String b => a;
    native shared String a => "hello";
}
```

since in the `native("jvm")` declaration, adding `print("");` might cause a merged class to look like:

```ceylon
shared class ClassA() {
    shared String b => a;
    shared String a => "hello";
    print("");
}
```
which is illegal per the spec due to initialization rules.

But putting the `native("jvm")` statements before the defaults may also cause problems:
```ceylon
shared class ClassA() {
    print(a);
    shared String b => a;
    shared String a => "hello";
}
```
which is also prohibited.

It seems like the merged result needs type checking, but the errors might be confusing.

**Comment by quintesse** [comment] 2015-10-19 14:48
And if we prohibit statements in both? Requiring the use of constructors if you want to do any initialization?

**Comment by gavinking** [comment] 2015-10-19 14:57
Can this be rescheduled for 1.3?

**Comment by quintesse** [comment] 2015-10-19 15:07
@gavinking sure, although I'd prefer then to have the most restrictive set of rules in place before that if possible. The idea being it's way easier to relax rules than to impose them when people have already writing code that depends on it.
(Right now I could push code that prohibits statements in headers and requires declarations to appear in the same order)

**Comment by jvasileff** [comment] 2015-10-19 15:15
I think most restrictive would be disallowing statements and default implementations. The ordering isn't necessarily a problem (long term) in cases where *everything* is restated in the `native("jvm")` code, and short term, the rule would be "you must restate all declarations" (since they wouldn't have default impls.)

The thing is, the ordering restriction alone isn't sufficient (https://github.com/ceylon/ceylon-compiler/issues/2371#issuecomment-149236814).

**Comment by quintesse** [comment] 2015-10-19 15:22
> The thing is, the ordering restriction alone isn't sufficient 

@jvasileff But what about https://github.com/ceylon/ceylon-compiler/issues/2371#issuecomment-149237558 ? That would permit the default implementations and solve all ordering problems, right?

**Comment by jvasileff** [comment] 2015-10-19 15:36
It would take me a little while to think through constructors and come up with an opinion. But it's probably worth noting that this is also illegal:

```ceylon
shared class ClassA {
    shared String b => a;
    shared String a => "hello";
    shared new () { /* whatever */ }
}
```

**Comment by jvasileff** [comment] 2015-10-19 15:39
I guess the issue being, statements within a constructor are basically the same as statements in the initializer section.

**Comment by quintesse** [comment] 2015-10-19 15:45
Well that't not entirely true, at least there's no way that you'd have to worry about which statements to choose and in which order to add them the the resulting class. But I guess the problem remains with respect to which constructors would have to be added where and in which order. Pfff.

But yes, not allowing any implementation in the header class would have been the easiest solution, the whole problem was that there were already quite a number of places in the language module where this was done far before I aven started on this native busines.

**Comment by jvasileff** [comment] 2015-10-19 15:59
Right, I meant wrt to initialization. Constructors are basically eager, so their contents matter.

This is legal:
```ceylon
shared class ClassA {
    shared new () { print(""); }
    shared String a => "a";
}
```
but this isn't:
```ceylon
shared class ClassA {
    shared new () { print(a); }
    shared String a => "a";
}
```

**Comment by quintesse** [comment] 2015-10-19 16:04
It would simplify a whole lot of other things as well actually. And might even make it possible again to have native implementations in their own source files. Which must be a boon to people trying to create new backends because the question is always: where do you put the new implementations? You either convince "upstream" to include your backend or you will have to maintain your own branch where you merged your code with the rest.
With separate file s you could just add a `--source mybackend` and they would be picked up by the compiler automatically.

**Comment by jvasileff** [comment] 2015-10-19 16:14
That would be quite nice! And then, that doesn't seem too far off from being able to define `native("jvm")` overrides for non-`native` annotated toplevel classes and functions, with non-`native`s being fully implemented but optionally replaceable definitions. Just brainstorming here!

**Comment by davidfestal** [comment] 2015-10-19 21:03
@quintesse : having the various native implementations in distinct source files makes it very difficult for the IDE to manage them correctly. I tried at the beginning, but it was really terrible.

**Comment by quintesse** [comment] 2015-10-19 21:05
@davidfestal I know, but we can't let our language be limited by our tools, right now there just isn't anyway someone could add a new backend.

**Comment by davidfestal** [comment] 2015-10-19 21:15
And do you plan to change this before 1.2 also ? Because this might involve much work on the IDE side to support it.

**Comment by quintesse** [comment] 2015-10-19 22:33
No no, don't worry ^^

**Closed** 2015-10-20 16:21 UTC
Labels: BUG, native

**Comment by quintesse** [comment] 2015-10-20 16:35
I at least fixed the problem described in this issue so I'll consider this closed.
