### ISSUE TITLE
Expose Method and Value for Java bean getters, setters 

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2023] opened 2015-01-28 13:23 UTC
Since I've fixed #2019 I think we need an issue to track the suggestion that the model loaded exposes the getter and setter `Method`s for Java properties as well as a `Value`.

**Comment by tombentley** [comment] 2015-01-28 13:25
Would doing this break the workaround for #2020?

**Comment by FroMage** [comment] 2015-01-28 13:25
Dupe of #1234.

**Closed by FroMage** 2015-01-28 13:25 UTC
Labels: FEATURE, interoperability, model-loader
