### ISSUE TITLE
Compiler bug message when I try to build this

### ISSUE THREAD

**Issue by lahwran** [ceylon/ceylon-compiler#1965] opened 2014-12-11 16:50 UTC
as of this commit: https://github.com/lahwran/tree-of-life/commit/3c665897b72036763d17bbabc2cdebaa1f49abe8  
(path in the repo: https://github.com/lahwran/tree-of-life/tree/3c665897b72036763d17bbabc2cdebaa1f49abe8/optimizer/source/treeoflife/optimize )  
I'm getting this message on build:

```
warning: It looks like you are using class files from a Java newer than 1.7.
  Everything should work well, but if not, let us know at https://github.com/ceylon/ceylon-compiler/issues.
  In the near future, the Ceylon compiler will be upgraded to handle Java 1.8.
error: compiler bug: unhandled declaration treeoflife.optimize::Gene with type TypeAlias at com.redhat.ceylon.compiler.java.codegen.AbstractTransformer.makeReifiedTypeArgument(AbstractTransformer.java:4538)
error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:317)
error: compiler bug: visitor didn't yield any result at unknown
Note: Created module treeoflife.optimize/0.0.1
ceylon compile: There were 3 errors
```

To see it happen:

```bash
git clone https://github.com/lahwran/tree-of-life.git
git checkout 3c665897b72036763d17bbabc2cdebaa1f49abe8
cd tree-of-life/optimizer/
# if you don't have java 8, edit source/treeoflife/optimize/module.ceylon to refer to 7
# maybe the bug will still happen?
ceylon compile treeoflife.optimize
```

**Comment by tombentley** [comment] 2015-01-14 12:37
@lahwran I'm also unable to reproduce with the compiler on master. Are you able to use a more recent compiler than 1.1.0 to confirm this bug no longer exists?

@lucaswerkmeister thanks for your `sed`.

**Comment by FroMage** [comment] 2015-01-22 09:26
@lahwran I'm going to close this because we think it's fixed and we can't reproduce, but if you can reproduce on the current master, please reopen.

**Closed by FroMage** 2015-01-22 09:26 UTC
Labels: BUG, UNREPRODUCIBLE
